### ISSUE TITLE
Milestone 1 requirements

### ISSUE THREAD

**Issue by trebi** [Qerts/pa165-java#3]
- [x] create a project in a Github repository that is publicly accessible (for read) choose a short and descriptive name. Create some project wiki to publish other information for your project.
- [x] on the project wiki there will be a project description, a use case diagram and a class diagram for entity classes. There will be at least two user roles in the use case diagram. Associations between entities will be present in the class diagram.  
- [x] create 4 entity classes for your project.
- [x] create a DAO layer interface (with proper javadoc).
- [x] create the JPA implementation of the DAO classes (CRUD operations are enough for the first checkpoint).
- [x] create unit tests for DAO classes (use in-memory database).
- [x] every team member should work with different entities on different parts of the project (e.g. member 1 will create implementation of DAO for entity A, but member 2 will create unit test for entity A). In every class there will  be javadoc @author with the name of the class author. Also you must commit into Git only the changes that you made yourself. If you commit on behalf of somebody else this will not be regarded as his work!
- [x] the project will be built using maven, and make sure you have all dependencies correctly configured, so it is possible to build it using just the command line.

**Comment by trebi** [comment]
Somebody please check this and then close the issue. I think it's all (except #1).

**Comment by JozeFe** [comment]
Good job guys.
