### ISSUE TITLE
Implement Facades

### ISSUE THREAD

**Issue by trebi** [Qerts/pa165-java#38]
**TASK: Select an Actor and the use case from the Use Case Diagram and implement it using Facade.** You will also need to implement appropriate service(s) and extends DAOs (and eventually also entities) accordingly.

**Assigned work**:
- [x] - Employee facade - @JozeFe - PR #39
- [x] - Journey facade - @msmidik  - PR #40
- [x] - Vehicle facade - @Qerts - PR #41
- [x] - Inspection facade - @trebi - PR #42

**DEADLINE: Thursday evening.**

**Before you start working, please write here to the comments, or to the Slack, which facade and which use cases will you implement.** Remember, we need to implement at least two non-trivial use cases, fully cover our services with unit tests (mocking DAOs), be aware of exceptions: services should work only with `DataAccessException`s; and finally implement some really simple (unit? integration?) test for facade.

Here is the drawing with my proposal of possible facades and their methods: 
![facades](https://cloud.githubusercontent.com/assets/1706766/20546305/867a8db4-b114-11e6-8f07-3131e6430b35.jpg)

Inspired from our Use Case Diagram:
![](https://raw.githubusercontent.com/Qerts/pa165-java/master/docs/diagrams/UseCaseDiagram.png)

**Comment by JozeFe** [comment]
I'm doing Employee facade
