### ISSUE TITLE
some bugs and todo

### ISSUE THREAD

**Issue by msmidik** [Qerts/pa165-java#65]
- [ ] (TODO) implement create, update, delete/disable operations from web

- [ ] (BUG) inspection intervals for individual vehicle do not display in vehicle detail (under serviceman menu)

- [ ] (BUG) available vehicles not shown for logged user but for user id 1 (hardcoded in line 44 template.tag)
